Presentation.MVC/Controllers/PatientsController.cs
using Domain;
using Domain.Dto;
using Presentation.MVC.Models;
using Repository.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Presentation.MVC.Controllers
{
    public class PatientsController : Controller
    {
        private readonly IRepositoryPatient _repositoryPatient;

        
        public PatientsController(IRepositoryPatient repositoryPatient)
        {
            _repositoryPatient = repositoryPatient;
        }

        // GET: Patient
        public ActionResult Index()
        {
            var dtos = _repositoryPatient.ShortInfoPatient();
            return View(dtos);
        }

        [HttpGet]
       public ActionResult AboutPatient()
        {

            var patients = _repositoryPatient.AllPatients();
            //var patientModel = new PatientDetailViewModel { Id = patient.Id, IDNP=patient.IDNP, Name = patient.Name, Surname = patient.Surname, BirthDate = patient.BirthDate, Gender = patient.Gender, AdressHome = patient.AdressHome, PhoneNumber = patient.PhoneNumber };
            IList<PatientDetailViewModel> patientModel = new List<PatientDetailViewModel>();
            foreach (var patient in patients)
            {
                var patientViewTemp = new PatientDetailViewModel();
                patientModel.Add(patientViewTemp.GetPatientViewModel(patient));
            }
            
            return View(patientModel);
        }

        [HttpGet]
        public ActionResult CreatePatient()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreatePatient(CreatePatientModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var patient = model.MapToPatient();
            _repositoryPatient.Save(patient);

            return RedirectToAction("AboutPatient");
        }


        [HttpGet]
        public ActionResult EditPatient(long id)
        {
            var patient = _repositoryPatient.Get<Patient>(id);
            var patientModel = new EditPatientModel { Id = patient.Id, Name = patient.Name, Surname = patient.Surname, Birthday = patient.BirthDate, Gender=patient.Gender, AdressHome = patient.AdressHome, PhoneNumber = patient.PhoneNumber };
            return View(patientModel);
        }

        [HttpPost]
        public ActionResult EditPatient(EditPatientModel patient)
        {
            var existingPatient = _repositoryPatient.Get<Patient>(patient.Id);

            existingPatient.Name = patient.Name;
            existingPatient.Surname = patient.Surname;
            existingPatient.AdressHome = patient.AdressHome;
            existingPatient.Gender = patient.Gender;
            existingPatient.PhoneNumber = patient.PhoneNumber;
            existingPatient.BirthDate = patient.Birthday;

            _repositoryPatient.Save(existingPatient);


            return RedirectToAction("AboutPatient");
        }

        public ActionResult DetailsPatient(long id)
        {
            Patient patient = _repositoryPatient.Get<Patient>(id);
            PatientDetailViewModel patientModel = new PatientDetailViewModel();
            patientModel.GetPatientViewModel(patient);
            return View(patientModel);
        }

        //Get Patient's details
        public ActionResult DeletePatient(long id)
        {
            Patient patient = _repositoryPatient.Get<Patient>(id);
            if (patient == null)
                return HttpNotFound();
            PatientDetailViewModel patientModel = new PatientDetailViewModel();
            patientModel.GetPatientViewModel(patient);
            return View(patientModel);
        }

        public ActionResult DeletePatientConfirm(long id)
        {
            var patient = _repositoryPatient.Get<Patient>(id);
            _repositoryPatient.Delete(patient);

            return RedirectToAction("AboutPatient");
        }
    }
}

Presentation.MVC/Views/Patients/AboutPatient.cshtml
@model IEnumerable<Presentation.MVC.Models.PatientDetailViewModel>

@{
    ViewBag.Title = "About Patient";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Patients</h2>

<p>
    <a href="@Url.Action("CreatePatient", "Patients")">
        <img src="@Url.Content("~/Foto/icon_user_add.jpg")" />
    </a>
    @*@Html.ActionLink("Create New", "CreatePatient")*@
</p>
<table class="table">
    <tr>
        
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Surname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BirthDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
       
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Surname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BirthDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Gender)
        </td>
        
        <td>
            <a href="@Url.Action("EditPatient", "Patients", new { id = item.Id })">
                <img src="@Url.Content("~/Foto/icon_edit.png")" />
            </a>
            <a href="@Url.Action("DetailsPatient", "Patients", new { id = item.Id })">
                <img src="@Url.Content("~/Foto/icon_details.png")" />
            </a>
            <a href="@Url.Action("DeletePatient", "Patients", new { id = item.Id })">
                <img src="@Url.Content("~/Foto/icon_delete.png")" />
            </a>

            @*@Html.ActionLink("Edit", "EditPatient", new { id = item.Id }) |
            @Html.ActionLink("Details", "DetailsPatient", new { id=item.Id}) |
            @Html.ActionLink("Delete", "DeletePatient", new { id=item.Id  })*@
            
        </td>
    </tr>
}

</table>

Presentation.MVC/Views/Patients/CreatePatient.cshtml
@model Presentation.MVC.Models.CreatePatientModel

@{
    ViewBag.Title = "CreatePatient";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create Patient</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @*<h4>CreatePatientModel</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IDNP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IDNP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IDNP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Gender)
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdressHome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdressHome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdressHome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "AboutPatient")
</div>

Presentation.MVC/Views/Patients/DeletePatient.cshtml
@model Presentation.MVC.Models.PatientDetailViewModel

@{
    ViewBag.Title = "DeletePatient";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete Patient</h2>

<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IDNP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IDNP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdressHome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdressHome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Delete", "DeletePatientConfirm", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "AboutPatient")
</p>

Presentation.MVC/Views/Patients/DetailsPatient.cshtml
@model Presentation.MVC.Models.PatientDetailViewModel

@{
    ViewBag.Title = "DetailsPatient";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details Patient</h2>

<div>
    @*<h4>PatientDetailViewModel</h4>*@
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IDNP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IDNP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdressHome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdressHome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

    </dl>
</div>
<p>
   
    @Html.ActionLink("Back to List", "AboutPatient")
</p>

Presentation.MVC/Views/Patients/EditPatient.cshtml
@model Presentation.MVC.Models.EditPatientModel

@{
    ViewBag.Title = "EditPatient";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit Patient</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Birthday, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Birthday, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Gender)
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdressHome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdressHome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdressHome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "AboutPatient")
</div>

Presentation.MVC/Views/Patients/Index.cshtml
@model List<Domain.Dto.PatientRedusDto>
@{
    ViewBag.Title = "Index";
}
    <h2>Patients</h2>
    @foreach (var patient in Model)
    {
        //pot face un table

        <p> <a href="@Url.Action("EditPatient", new { id = patient.IdPatient})">@patient.Name @patient.Surname</a>    @patient.CountSicknessHistories</p>

    }