Presentation.MVC/Controllers/DoctorsController.cs
using Domain;
using Domain.Dto;
using Presentation.MVC.Models;
using Repository.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Presentation.MVC.Controllers
{
    public class DoctorsController : Controller
    {
        private readonly IRepositoryDoctor _repositoryDoctor;
        public DoctorsController(IRepositoryDoctor repositoryDoctor)
        {
            _repositoryDoctor = repositoryDoctor;
        }

        // GET: Doctors
        public ActionResult AboutDoctors()
        {
            return View();
        }

        [HttpGet]
        public ActionResult ManageDoctors()
        {
            var doctorsDto = _repositoryDoctor.ShortInfoDoctor();

            IList<DoctorModel> doctorModel = new List<DoctorModel>();
            foreach (var doctor in doctorsDto)
            {
                var doctorTemp = new DoctorModel();
                doctorModel.Add(doctorTemp.GetDoctorModel(doctor));
            }
            return View(doctorModel);
        }

        //[HttpGet]
        //public ActionResult Create()
        //{
        //    return View();
        //}


        // GET: Car/Create
        [HttpGet]
        public PartialViewResult Create()
        {
            var items = new List<SelectListItem>();

            IList<MedicalSpecialtyForCreationDoctorDto> medicalSpecialties = _repositoryDoctor.ListMedicalSpecialtyFoCreationDoctor();

            foreach (var ms in medicalSpecialties)
            {
                items.Add(new SelectListItem { Text = ms.MedicalSpecialtyName, Value = ms.Id.ToString() });
            }

            var createDoctorModel = new CreateDoctorModel(items);
           
            return PartialView(createDoctorModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateDoctorModel model)
        {
            if (!ModelState.IsValid)
                return View(model);
            var doctor = model.MapToDoctor();
            _repositoryDoctor.Save(doctor);
            return RedirectToAction("ManageDoctors");

        }

    }
}

Presentation.MVC/Views/Shared/EnumDropdown.cshtml
@model Enum

@Html.ValidationSummary(true, "", new { @class = "text-danger" })
<div class="form-group">
    @Html.LabelFor(model => model, new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EnumDropDownListFor(model => model, new { @class = "form-control" })

    </div>
</div>

Presentation.MVC/Views/Shared/MedicalSpecialty.cshtml
@model IEnumerable<Domain.Dto.MedicalSpecialtyForCreationDoctorDto>

<p>
    @Html.ActionLink("Create New", "Create")
</p>




<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MedicalSpecialtyName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MedicalSpecialtyName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

Presentation.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/AboutStyle.css" rel="stylesheet" />
    <script src="~/scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Patients", "AboutPatient", "Patients", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Our Doctors", "AboutDoctors", "Doctors", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Manage Doctors", "ManageDoctors", "Doctors", new { area = "" }, new { @class = "navbar-brand" })

                @*@Html.ActionLink("Short Info", "Index", "Patients", new { area = "" }, new { @class = "navbar-brand" })*@
                @*@Html.ActionLink("Create Patient", "CreatePatient", "Patients", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>